---
app:
    protocol: http
    hostname: ~
    port: ~
    debug: false

database:
    client:
        type: mongodb
        timeZone: UTC
    connection: {}
    options: {}

logger:
    log_level: ~
    morgan_format: ~